AWSTemplateFormatVersion: '2010-09-09'
Description: AWS EKS Cluster

Resources:

  EKSCluster:
    Type: AWS::EKS::Cluster
    DeletionPolicy: Retain
    Properties:
      Name: sandbox-cluster
      Version: "1.32"
      RoleArn: "arn:aws:iam::767398111149:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS"
      KubernetesNetworkConfig:
        IpFamily: ipv4
        ServiceIpv4Cidr: 10.100.0.0/16
      ResourcesVpcConfig:
        EndpointPrivateAccess: true
        EndpointPublicAccess: true
        PublicAccessCidrs:
          - "223.237.168.149/32"
        SecurityGroupIds:
          - "sg-02e0affa752353c1a"
        SubnetIds:
          - "subnet-0c12641a01190da9c"
          - "subnet-09a423c0a6bde4c32"
          - "subnet-0afa393c4041daa00"
          - "subnet-04fd8d9586d4f33b8"
      Tags:
        - Key: cluster
          Value: sandbox
        - Key: provisionedby
          Value: cloud-formation-template

  EKSClusterAddOnsEFSCSI:
    Type: AWS::EKS::Addon
    DeletionPolicy: Retain
    Properties:
      AddonName: aws-efs-csi-driver
      AddonVersion: "v2.1.3-eksbuild.1"
      ClusterName: sandbox-cluster
      ResolveConflicts: OVERWRITE

  EKSClusterAddOnsEBSCSI:
    Type: AWS::EKS::Addon
    DeletionPolicy: Retain
    Properties:
      AddonName: aws-ebs-csi-driver
      AddonVersion: "v1.38.1-eksbuild.2"
      ClusterName: sandbox-cluster
      ServiceAccountRoleArn: arn:aws:iam::767398111149:role/sandbox-cluster-ebs-csi-driver
      ResolveConflicts: OVERWRITE

  EKSClusterAddOnsVPCCNI:
    Type: AWS::EKS::Addon
    DeletionPolicy: Retain
    Properties:
      AddonName: vpc-cni
      AddonVersion: "v1.19.2-eksbuild.1"
      ClusterName: sandbox-cluster
      ResolveConflicts: OVERWRITE

  EKSClusterAddOnsKubeProxy:
    Type: AWS::EKS::Addon
    DeletionPolicy: Retain
    Properties:
      AddonName: kube-proxy
      AddonVersion: "v1.30.6-eksbuild.3"
      ClusterName: sandbox-cluster
      ResolveConflicts: OVERWRITE

  GeneralNodeGroup1:
    Type: AWS::EKS::Nodegroup
    DeletionPolicy: Delete
    Properties:
      ClusterName: sandbox-cluster
      NodegroupName: general-worker-nodegroup-1
      ScalingConfig:
        MinSize: 1
        DesiredSize: 1
        MaxSize: 3
      Subnets:
        - "subnet-09a423c0a6bde4c32 "
        - "subnet-0afa393c4041daa00 "
      CapacityType: ON_DEMAND
      NodeRole: arn:aws:iam::767398111149:role/aws-service-role/eks-nodegroup.amazonaws.com/AWSServiceRoleForAmazonEKSNodegroup
      Tags:
        provisionedby: CloudFormation
        Environment: sandbox-cluster
      Taints:
        - Effect: NO_SCHEDULE
          key: app
          value: true
      Version: "1.32"

  GeneralNodeGroup2:
    Type: AWS::EKS::Nodegroup
    DeletionPolicy: Delete
    Properties:
      ClusterName: sandbox-cluster
      NodegroupName: general-worker-nodegroup-2
      ScalingConfig:
        MinSize: 1
        DesiredSize: 1
        MaxSize: 3
      Subnets:
        - "subnet-0c12641a01190da9c"
        - "subnet-04fd8d9586d4f33b8"
      CapacityType: ON_DEMAND
      NodeRole: arn:aws:iam::767398111149:role/aws-service-role/eks-nodegroup.amazonaws.com/AWSServiceRoleForAmazonEKSNodegroup
      Tags:
        provisionedby: CloudFormation
        Environment: sandbox-cluster
      Taints:
        - Effect: NO_SCHEDULE
          key: app
          value: true
      Version: "1.32"
cluster-config.yaml [+]                                                                     107,25         91%
-- INSERT --
